name: Update Index

on:
  push:
    branches:
      - main  # 根据你的默认分支修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # 使用 node 16

    - name: Generate book list
      run: |
        echo "<!DOCTYPE html><html><head><title>Trading Learning Library</title><style>body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; } h1 { color: #333; } ul { list-style-type: none; padding: 0; } li { margin: 10px 0; } a { text-decoration: none; color: #007bff; } a:hover { text-decoration: underline; }</style></head><body><h1>Trading Learning Library</h1><ul>" > index.html
        for file in lib/*; do
          filename=$(basename "$file")
          echo "<li><a href=\"$file\" download>$filename</a></li>" >> index.html
        done
        echo "</ul></body></html>" >> index.html

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.html
        git commit -m 'Update index.html with book list'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

